// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: transport/internet/shadowquic/config.proto

package shadowquic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JlsUpstream       string                 `protobuf:"bytes,1,opt,name=jls_upstream,json=jlsUpstream,proto3" json:"jls_upstream,omitempty"`
	ServerName        string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Alpn              []string               `protobuf:"bytes,3,rep,name=alpn,proto3" json:"alpn,omitempty"`
	CongestionControl string                 `protobuf:"bytes,4,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	ZeroRtt           bool                   `protobuf:"varint,5,opt,name=zero_rtt,json=zeroRtt,proto3" json:"zero_rtt,omitempty"`
	MaxIdleTimeoutMs  int64                  `protobuf:"varint,6,opt,name=max_idle_timeout_ms,json=maxIdleTimeoutMs,proto3" json:"max_idle_timeout_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_shadowquic_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_shadowquic_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_shadowquic_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetJlsUpstream() string {
	if x != nil {
		return x.JlsUpstream
	}
	return ""
}

func (x *Config) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Config) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *Config) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *Config) GetZeroRtt() bool {
	if x != nil {
		return x.ZeroRtt
	}
	return false
}

func (x *Config) GetMaxIdleTimeoutMs() int64 {
	if x != nil {
		return x.MaxIdleTimeoutMs
	}
	return 0
}

var File_transport_internet_shadowquic_config_proto protoreflect.FileDescriptor

const file_transport_internet_shadowquic_config_proto_rawDesc = "" +
	"\n" +
	"*transport/internet/shadowquic/config.proto\x12\x22xray.transport.intern" +
	"et.shadowquic\x22\xd9\x01" +
	"\n" +
	"\x06Config\x12!" +
	"\n" +
	"\x0cjls_upstream\x18\x01 \x01(\x09R\x0bjlsUpstream\x12\x1f" +
	"\n" +
	"\x0bserver_name\x18\x02 \x01(\x09R" +
	"\n" +
	"serverName\x12\x12" +
	"\n" +
	"\x04alpn\x18\x03 \x03(\x09R\x04alpn\x12-" +
	"\n" +
	"\x12congestion_control\x18\x04 \x01(\x09R\x11congestionControl\x12\x19" +
	"\n" +
	"\x08zero_rtt\x18\x05 \x01(\x08R\x07zeroRtt\x12-" +
	"\n" +
	"\x13max_idle_timeout_ms\x18\x06 \x01(\x03R\x10maxIdleTimeoutMsB9Z7github" +
	".com/xtls/xray-core/transport/internet/shadowquicb\x06proto3"
var (
	file_transport_internet_shadowquic_config_proto_rawDescOnce sync.Once
	file_transport_internet_shadowquic_config_proto_rawDescData []byte
)

func file_transport_internet_shadowquic_config_proto_rawDescGZIP() []byte {
	file_transport_internet_shadowquic_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_shadowquic_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_shadowquic_config_proto_rawDesc), len(file_transport_internet_shadowquic_config_proto_rawDesc)))
	})
	return file_transport_internet_shadowquic_config_proto_rawDescData
}

var file_transport_internet_shadowquic_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_shadowquic_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.shadowquic.Config
}
var file_transport_internet_shadowquic_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_shadowquic_config_proto_init() }
func file_transport_internet_shadowquic_config_proto_init() {
	if File_transport_internet_shadowquic_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_shadowquic_config_proto_rawDesc), len(file_transport_internet_shadowquic_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_shadowquic_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_shadowquic_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_shadowquic_config_proto_msgTypes,
	}.Build()
	File_transport_internet_shadowquic_config_proto = out.File
	file_transport_internet_shadowquic_config_proto_goTypes = nil
	file_transport_internet_shadowquic_config_proto_depIdxs = nil
}
