// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proxy/sudoku/config.proto

package sudoku

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account identifies a Sudoku client by its Available Private Key (hex).
// UserHash = hex(sha256(decoded_key_bytes)[:8]) is used for allowlisting.
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available Private Key hex (128 hex chars for split key) or raw key material hex.
	PrivateKey string `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Optional precomputed user hash (16 hex chars). When empty, derived from private_key.
	UserHash      string `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_sudoku_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_sudoku_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_sudoku_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Account) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Server key: Master Public Key hex (or shared PSK).
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// chacha20-poly1305 | aes-128-gcm | none
	AeadMethod string `protobuf:"bytes,3,opt,name=aead_method,json=aeadMethod,proto3" json:"aead_method,omitempty"`
	PaddingMin uint32 `protobuf:"varint,4,opt,name=padding_min,json=paddingMin,proto3" json:"padding_min,omitempty"`
	PaddingMax uint32 `protobuf:"varint,5,opt,name=padding_max,json=paddingMax,proto3" json:"padding_max,omitempty"`
	// prefer_entropy | prefer_ascii | up_ascii_down_entropy | up_entropy_down_ascii
	TableType          string   `protobuf:"bytes,6,opt,name=table_type,json=tableType,proto3" json:"table_type,omitempty"`
	EnablePureDownlink bool     `protobuf:"varint,7,opt,name=enable_pure_downlink,json=enablePureDownlink,proto3" json:"enable_pure_downlink,omitempty"`
	CustomTable        string   `protobuf:"bytes,8,opt,name=custom_table,json=customTable,proto3" json:"custom_table,omitempty"`
	CustomTables       []string `protobuf:"bytes,9,rep,name=custom_tables,json=customTables,proto3" json:"custom_tables,omitempty"`
	HandshakeTimeout   uint32   `protobuf:"varint,10,opt,name=handshake_timeout,json=handshakeTimeout,proto3" json:"handshake_timeout,omitempty"`
	DisableHttpMask    bool     `protobuf:"varint,11,opt,name=disable_http_mask,json=disableHttpMask,proto3" json:"disable_http_mask,omitempty"`
	// legacy | stream | poll | auto | ws
	HttpMaskMode string `protobuf:"bytes,12,opt,name=http_mask_mode,json=httpMaskMode,proto3" json:"http_mask_mode,omitempty"`
	PathRoot     string `protobuf:"bytes,13,opt,name=path_root,json=pathRoot,proto3" json:"path_root,omitempty"`
	// host:port for suspicious handshake fallback
	Fallback string `protobuf:"bytes,14,opt,name=fallback,proto3" json:"fallback,omitempty"`
	// off | auto | on
	Multiplex     string `protobuf:"bytes,15,opt,name=multiplex,proto3" json:"multiplex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_sudoku_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_sudoku_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_sudoku_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServerConfig) GetAeadMethod() string {
	if x != nil {
		return x.AeadMethod
	}
	return ""
}

func (x *ServerConfig) GetPaddingMin() uint32 {
	if x != nil {
		return x.PaddingMin
	}
	return 0
}

func (x *ServerConfig) GetPaddingMax() uint32 {
	if x != nil {
		return x.PaddingMax
	}
	return 0
}

func (x *ServerConfig) GetTableType() string {
	if x != nil {
		return x.TableType
	}
	return ""
}

func (x *ServerConfig) GetEnablePureDownlink() bool {
	if x != nil {
		return x.EnablePureDownlink
	}
	return false
}

func (x *ServerConfig) GetCustomTable() string {
	if x != nil {
		return x.CustomTable
	}
	return ""
}

func (x *ServerConfig) GetCustomTables() []string {
	if x != nil {
		return x.CustomTables
	}
	return nil
}

func (x *ServerConfig) GetHandshakeTimeout() uint32 {
	if x != nil {
		return x.HandshakeTimeout
	}
	return 0
}

func (x *ServerConfig) GetDisableHttpMask() bool {
	if x != nil {
		return x.DisableHttpMask
	}
	return false
}

func (x *ServerConfig) GetHttpMaskMode() string {
	if x != nil {
		return x.HttpMaskMode
	}
	return ""
}

func (x *ServerConfig) GetPathRoot() string {
	if x != nil {
		return x.PathRoot
	}
	return ""
}

func (x *ServerConfig) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

func (x *ServerConfig) GetMultiplex() string {
	if x != nil {
		return x.Multiplex
	}
	return ""
}

var File_proxy_sudoku_config_proto protoreflect.FileDescriptor

const file_proxy_sudoku_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/sudoku/config.proto\x12\x11xray.proxy.sudoku\x1a\x1acommon/protocol/user.proto\"G\n" +
	"\aAccount\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\"\xa4\x04\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1f\n" +
	"\vaead_method\x18\x03 \x01(\tR\n" +
	"aeadMethod\x12\x1f\n" +
	"\vpadding_min\x18\x04 \x01(\rR\n" +
	"paddingMin\x12\x1f\n" +
	"\vpadding_max\x18\x05 \x01(\rR\n" +
	"paddingMax\x12\x1d\n" +
	"\n" +
	"table_type\x18\x06 \x01(\tR\ttableType\x120\n" +
	"\x14enable_pure_downlink\x18\a \x01(\bR\x12enablePureDownlink\x12!\n" +
	"\fcustom_table\x18\b \x01(\tR\vcustomTable\x12#\n" +
	"\rcustom_tables\x18\t \x03(\tR\fcustomTables\x12+\n" +
	"\x11handshake_timeout\x18\n" +
	" \x01(\rR\x10handshakeTimeout\x12*\n" +
	"\x11disable_http_mask\x18\v \x01(\bR\x0fdisableHttpMask\x12$\n" +
	"\x0ehttp_mask_mode\x18\f \x01(\tR\fhttpMaskMode\x12\x1b\n" +
	"\tpath_root\x18\r \x01(\tR\bpathRoot\x12\x1a\n" +
	"\bfallback\x18\x0e \x01(\tR\bfallback\x12\x1c\n" +
	"\tmultiplex\x18\x0f \x01(\tR\tmultiplexBU\n" +
	"\x15com.xray.proxy.sudokuP\x01Z&github.com/xtls/xray-core/proxy/sudoku\xaa\x02\x11Xray.Proxy.Sudokub\x06proto3"

var (
	file_proxy_sudoku_config_proto_rawDescOnce sync.Once
	file_proxy_sudoku_config_proto_rawDescData []byte
)

func file_proxy_sudoku_config_proto_rawDescGZIP() []byte {
	file_proxy_sudoku_config_proto_rawDescOnce.Do(func() {
		file_proxy_sudoku_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_sudoku_config_proto_rawDesc), len(file_proxy_sudoku_config_proto_rawDesc)))
	})
	return file_proxy_sudoku_config_proto_rawDescData
}

var file_proxy_sudoku_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_sudoku_config_proto_goTypes = []any{
	(*Account)(nil),       // 0: xray.proxy.sudoku.Account
	(*ServerConfig)(nil),  // 1: xray.proxy.sudoku.ServerConfig
	(*protocol.User)(nil), // 2: xray.common.protocol.User
}
var file_proxy_sudoku_config_proto_depIdxs = []int32{
	2, // 0: xray.proxy.sudoku.ServerConfig.users:type_name -> xray.common.protocol.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_sudoku_config_proto_init() }
func file_proxy_sudoku_config_proto_init() {
	if File_proxy_sudoku_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_sudoku_config_proto_rawDesc), len(file_proxy_sudoku_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_sudoku_config_proto_goTypes,
		DependencyIndexes: file_proxy_sudoku_config_proto_depIdxs,
		MessageInfos:      file_proxy_sudoku_config_proto_msgTypes,
	}.Build()
	File_proxy_sudoku_config_proto = out.File
	file_proxy_sudoku_config_proto_goTypes = nil
	file_proxy_sudoku_config_proto_depIdxs = nil
}
